### ISSUE TITLE
[BUG] Unable to Correctly Identify and Generate Paths for Sub-Pages

### ISSUE THREAD

**Issue by luxlogica** [ThePoddi/kirby-robots#1]
In Kirby, the _$page->uid()_ function does not return a 'unique id'. It returns only the name of the content folder for the page, without the sorting number prefix. It is equivalent to the very last section of the URL for the page, and it does not uniquely identify the page. It is, indeed, possible to have 2 pages in different locations with the same UID. For example: for the page in URL _http://example.com/portfolio/testimonials/quote-1_, the UID is just 'quote-1'. It is quite possible for us to have another page with the same UID, somewhere else in the site.

To uniquely identify a page in the site, we can use the **_$page->uri()_** function. In the example above: the uri would be 'portfolio/testimonials/quote-1'.

Because right now the code is using _uid()_ instead of _uri()_, it is not identifying pages correctly, and only generating correct 'Disallow' page paths for top-level pages - ie., the code is actually unable to generate paths for sub-pages.

Example: let's say that I want to exclude all articles from my blog. The articles are all sub-pages of the 'blog' page, so their url will be something like _http://example.com/blog/article1_. If I want to exclude them, according to the instructions I should just add the 'article' template to the list of templates to be ignored - like this:

```
c::set( 'robots.ignore.templates', ['article' , 'error'] );
```

Now, if I view the _robots.txt_ file that is generated, I'd expect to find a long list of disallowed pages, like:

```
Disallow: /blog/article-1
Disallow: /blog/article-2
Disallow: /blog/article-3
```

Instead, what we're getting is:

```
Disallow: /article-1
Disallow: /article-2
Disallow: /article-3
```

Changing the function used to identify pages from _uid()_ to _uri()_ should fix this.

**Comment by ThePoddi** [comment]
Thanks a lot!
